=== digabi/exam-engine/packages/mastering/schema/exam.xsd
<xs:schema xmlns:e="http://ylioppilastutkinto.fi/exam.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xhtml="http://www.w3.org/1999/xhtml" targetNamespace="http://ylioppilastutkinto.fi/exam.xsd" elementFormDefault="qualified" version="1.0" xml:lang="fi">

  <!-- Import relevant XHTML subset -->
  <xs:import namespace="http://www.w3.org/1999/xhtml" schemaLocation="xhtml11.xsd" />

  <xs:element name="exam">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="e:languages" />
        <xs:element name="exam-title" type="e:Flow" minOccurs="0" />
        <xs:element name="exam-instruction" type="e:Flow" minOccurs="0" />
        <xs:element ref="e:table-of-contents" minOccurs="0" />
        <xs:element ref="e:external-material" minOccurs="0" />
        <xs:element ref="e:section" maxOccurs="unbounded" />
        <xs:element ref="e:references" minOccurs="0" />
        <xs:element name="exam-footer" type="e:Flow" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="exam-schema-version" type="e:exam-schema-version" />
      <xs:attribute name="date" type="xs:date" />
      <xs:attribute name="exam-code" type="xs:string" />
      <xs:attribute name="day-code" type="xs:string" />
      <xs:attribute name="exam-stylesheet" type="xs:string" />
      <xs:attribute name="max-answers" type="xs:positiveInteger" />
    </xs:complexType>

    <xs:key name="language-key">
      <xs:selector xpath=".//e:language" />
      <xs:field xpath="." />
    </xs:key>

    <xs:unique name="attachment-unique">
      <xs:selector xpath=".//e:attachment" />
      <xs:field xpath="@name" />
    </xs:unique>

    <xs:keyref name="lang-keyref" refer="e:language-key">
      <xs:selector xpath=".//e:*" />
      <xs:field xpath="@lang" />
    </xs:keyref>

    <xs:keyref name="attachment-link-keyref" refer="e:attachment-unique">
      <xs:selector xpath=".//e:attachment-link" />
      <xs:field xpath="@ref" />
    </xs:keyref>

  </xs:element>

  <xs:attributeGroup name="localizable">
    <xs:attribute name="lang" type="xs:language" />
  </xs:attributeGroup>

  <xs:attributeGroup name="stylable">
    <xs:attribute name="class" type="xs:NMTOKENS" />
  </xs:attributeGroup>

  <xs:attributeGroup name="hidable">
    <xs:attribute name="hidden" type="xs:boolean" use="optional" default="false">
      <xs:annotation>
        <xs:documentation>Piilotetaanko elementti koetilanteessa.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>

  <xs:simpleType name="exam-schema-version">
    <xs:restriction base="xs:string">
      <xs:enumeration value="0.1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="Flow" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:group ref="xhtml:xhtml.Flow.mix" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="LocalizableFlow" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:group ref="xhtml:xhtml.Flow.mix" />
    </xs:choice>
    <xs:attributeGroup ref="e:localizable" />
    <xs:attributeGroup ref="e:hidable" />
  </xs:complexType>

  <xs:element name="languages">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="language" type="xs:language" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="localization">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group ref="xhtml:xhtml.Flow.mix" />
      </xs:choice>
      <xs:attribute name="lang" type="xs:language" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="table-of-contents">
    <xs:complexType>
      <xs:sequence />
    </xs:complexType>
  </xs:element>

  <xs:element name="section">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="section-title" type="e:Flow" />
        <xs:element ref="e:audio-test" minOccurs="0" />
        <!-- TODO: Validate that section has at least one question. -->
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="section-instruction" type="e:Flow" />
          <xs:element ref="e:question" maxOccurs="unbounded" />
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="max-answers" type="xs:positiveInteger" />
      <xs:attribute name="cas-forbidden" type="xs:boolean" default="false" />
    </xs:complexType>
  </xs:element>

  <xs:element name="question">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="question-title" type="e:Flow" />
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="question-instruction" type="e:Flow" />
          <xs:element ref="e:external-material" />
          <xs:group ref="xhtml:xhtml.Flow.mix" />
          <xs:element ref="e:question" />
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="max-answers" type="xs:positiveInteger" />
    </xs:complexType>
  </xs:element>

  <xs:element name="external-material">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="e:attachment" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Attachments -->

  <xs:attributeGroup name="sourcable">
    <xs:attribute name="src" type="xs:string" use="required" />
  </xs:attributeGroup>

  <xs:element name="attachment">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="attachment-title" type="e:Flow" />
        <xs:group ref="xhtml:xhtml.Flow.mix" maxOccurs="unbounded" />
        <xs:element ref="e:reference" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:NMTOKEN" />
      <xs:attribute name="lang" type="xs:language" />
    </xs:complexType>
  </xs:element>

  <xs:element name="attachment-links">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="e:attachment-link" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="type" type="e:attachment-link-type" default="long" />
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="attachment-link-type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="short" />
      <xs:enumeration value="long" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="attachment-link">
    <xs:complexType>
      <xs:sequence />
      <xs:attribute name="ref" type="xs:NMTOKEN" use="required" />
      <xs:attribute name="type" type="e:attachment-link-type" default="long" />
    </xs:complexType>
  </xs:element>

  <xs:element name="image">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group ref="xhtml:xhtml.Flow.mix" />
      </xs:choice>
      <xs:attributeGroup ref="e:sourcable" />
      <xs:attributeGroup ref="e:localizable" />
      <xs:attributeGroup ref="e:stylable" />
    </xs:complexType>
  </xs:element>

  <xs:element name="image-overlay">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="e:image" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attributeGroup ref="e:localizable" />
    </xs:complexType>
  </xs:element>

  <xs:element name="video">
    <xs:complexType>
      <xs:sequence />
      <xs:attributeGroup ref="e:sourcable" />
      <xs:attributeGroup ref="e:localizable" />
      <xs:attributeGroup ref="e:stylable" />
    </xs:complexType>
  </xs:element>

  <xs:element name="audio-test">
    <xs:complexType>
      <xs:sequence />
      <xs:attributeGroup ref="e:sourcable" />
    </xs:complexType>
  </xs:element>

  <xs:element name="audio">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group ref="xhtml:xhtml.Flow.mix" />
      </xs:choice>
      <xs:attributeGroup ref="e:sourcable" />
      <xs:attribute name="times" type="xs:positiveInteger" />
      <xs:attributeGroup ref="e:localizable" />
      <xs:attributeGroup ref="e:stylable" />
    </xs:complexType>
  </xs:element>

  <xs:element name="audio-group">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group ref="xhtml:xhtml.Flow.mix" />
        <xs:element ref="e:question" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="file">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group ref="xhtml:xhtml.Flow.mix" />
      </xs:choice>
      <xs:attributeGroup ref="e:sourcable" />
      <xs:attributeGroup ref="e:localizable" />
      <xs:attributeGroup ref="e:stylable" />
    </xs:complexType>
  </xs:element>

  <!-- References -->

  <xs:element name="reference">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="author" type="e:LocalizableFlow" />
        <xs:element name="title" type="e:LocalizableFlow" />
        <xs:element name="publisher" type="e:LocalizableFlow" />
        <xs:element name="publication" type="e:LocalizableFlow" />
        <xs:element name="url" type="e:LocalizableFlow" />
        <xs:element name="publication-date" type="e:localizable-date" maxOccurs="unbounded" />
        <xs:element name="reference-date" type="e:localizable-date" maxOccurs="unbounded" />
        <xs:element name="modified-by" type="e:LocalizableFlow" />
        <xs:element name="translator" type="e:LocalizableFlow" />
        <xs:element name="translation-date" type="e:localizable-date" maxOccurs="unbounded" />
        <xs:element name="howpublished" type="e:LocalizableFlow" />
        <xs:element name="note" type="e:LocalizableFlow" />
      </xs:choice>
      <xs:attributeGroup ref="e:localizable" />
      <xs:attributeGroup ref="e:hidable" />
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="date">
    <xs:union memberTypes="xs:date xs:gYear" />
  </xs:simpleType>

  <xs:complexType name="localizable-date">
    <xs:simpleContent>
      <xs:extension base="e:date">
        <xs:attributeGroup ref="e:localizable" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:element name="references">
    <xs:complexType>
      <xs:sequence />
    </xs:complexType>
  </xs:element>

  <!-- Formulas -->

  <xs:element name="formula">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="mode" type="e:formula-mode" default="inline" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="formula-mode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="display" />
      <xs:enumeration value="inline" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Answer types -->

  <xs:group name="Answer.class">
    <xs:choice>
      <xs:element ref="e:text-answer" />
      <xs:element ref="e:hints" />
      <xs:element ref="e:scored-text-answers" />
      <xs:element ref="e:scored-text-answer" />
      <xs:element ref="e:choice-answer" />
      <xs:element ref="e:dropdown-answer" />
    </xs:choice>
  </xs:group>

  <xs:element name="text-answer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="hint" minOccurs="0" type="e:Flow" />
      </xs:sequence>
      <xs:attribute name="type" type="e:text-answer-type" default="single-line" />
      <xs:attribute name="max-score" type="xs:positiveInteger" use="required" />
      <xs:attributeGroup ref="e:stylable" />
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="text-answer-type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="single-line" />
      <xs:enumeration value="multi-line" />
      <xs:enumeration value="rich-text" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="hints">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:group ref="xhtml:xhtml.Flow.mix" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="scored-text-answers">
    <xs:annotation>
      <xs:documentation>
        Deprecated. Use
        <code>e:hints</code>
        instead.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:group ref="xhtml:xhtml.Flow.mix" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="scored-text-answer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="hint" minOccurs="0" type="e:Flow" />
        <xs:element ref="e:accepted-answer" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="type" type="e:text-answer-type" default="single-line" />
      <xs:attribute name="max-score" type="xs:positiveInteger" />
      <xs:attributeGroup ref="e:stylable" />
    </xs:complexType>
  </xs:element>

  <xs:element name="accepted-answer">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="score" type="xs:positiveInteger" use="required" />
          <xs:attributeGroup ref="e:localizable" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <!-- Choice answers -->

  <xs:simpleType name="ordering">
    <xs:restriction base="xs:string">
      <xs:enumeration value="random" />
      <xs:enumeration value="fixed" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="direction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vertical" />
      <xs:enumeration value="horizontal" />
    </xs:restriction>
  </xs:simpleType>

  <xs:attributeGroup name="orderable">
    <xs:attribute name="ordering" type="e:ordering" default="random" />
  </xs:attributeGroup>

  <xs:element name="choice-answer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="e:choice-answer-option" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="direction" type="e:direction" />
      <xs:attributeGroup ref="e:orderable" />
      <xs:attributeGroup ref="e:stylable" />
    </xs:complexType>
  </xs:element>

  <xs:element name="choice-answer-option">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:group ref="xhtml:xhtml.Flow.mix" />
      </xs:choice>
      <xs:attribute name="score" type="xs:integer" />
      <xs:attributeGroup ref="e:stylable" />
    </xs:complexType>
  </xs:element>

  <xs:element name="dropdown-answer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="e:dropdown-answer-option" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attributeGroup ref="e:orderable" />
      <xs:attributeGroup ref="e:stylable" />
    </xs:complexType>
  </xs:element>

  <xs:element name="dropdown-answer-option">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:group ref="xhtml:xhtml.Flow.mix" />
      </xs:choice>
      <xs:attribute name="score" type="xs:integer" />
      <xs:attributeGroup ref="e:stylable" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== digabi/exam-engine/packages/mastering/__tests__/fixtures/multiple_exam_types.xml
<?xml version="1.0" encoding="UTF-8"?>
<e:exam xmlns:e="http://ylioppilastutkinto.fi/exam.xsd" xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ylioppilastutkinto.fi/exam.xsd https://abitti.dev/schema/exam.xsd" exam-schema-version="0.3" date="2020-01-01">
  <e:exam-versions>
    <e:exam-version lang="fi-FI" exam-type="normal"/>
    <e:exam-version lang="fi-FI" exam-type="visually-impaired"/>
    <e:exam-version lang="fi-FI" exam-type="hearing-impaired"/>
  </e:exam-versions>
  <e:exam-instruction>
    <e:localization exam-type="normal visually-impaired">
      Tekstiä tavalliseen ja näkövammaisten kokeeseen.
    </e:localization>
    <e:localization exam-type="hearing-impaired">
      Tekstiä kuulovammaisten kokeeseen.
    </e:localization>
  </e:exam-instruction>
  <e:table-of-contents />
  <e:section>
    <e:section-title>Kuuntelutehtävät</e:section-title>
    <e:question>
      <e:question-title>Kaikille yhteinen tehtävä</e:question-title>
    </e:question>
    <e:question exam-type="normal hearing-impaired">
      <e:question-title>Kuuntelutehtävä</e:question-title>
    </e:question>
    <e:question exam-type="visually-impaired">
      <e:question-title>Näkövammaisten korvaava kuuntelutehtävä</e:question-title>
    </e:question>
  </e:section>
  <e:section>
    <e:section-title>Kirjalliset tehtävät</e:section-title>
    <e:question exam-type="normal hearing-impaired">
      <e:question-title>Kirjallinen tehtävä</e:question-title>
    </e:question>
    <e:question exam-type="visually-impaired">
      <e:question-title>Näkövammaisten korvaava kirjallinen tehtävä</e:question-title>
    </e:question>
  </e:section>
</e:exam>

=== digabi/exam-engine/packages/mastering/__tests__/fixtures/old_schema_version.xml
<?xml version="1.0" encoding="utf-8" ?>
<e:exam xmlns:e="http://ylioppilastutkinto.fi/exam.xsd" xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ylioppilastutkinto.fi/exam.xsd https://abitti.dev/schema/exam.xsd" exam-schema-version="0.1" date="2020-01-01" exam-code="A" day-code="X">
    <e:languages>
        <e:language>fi-FI</e:language>
        <e:language>sv-FI</e:language>
    </e:languages>
    <e:exam-title />
    <e:exam-instruction />
    <e:section>
        <e:section-title/>
        <e:section-instruction>Section without cas-forbidden attribute</e:section-instruction>
        <e:question>
            <e:question-title/>
        </e:question>
    </e:section>
    <e:section cas-forbidden="true">
        <e:section-title/>
        <e:section-instruction>Cas forbidden section 1</e:section-instruction>
        <e:question>
            <e:question-title/>
            <e:audio src="1.ogg">
                Audio file <em>description</em>
            </e:audio>
            <e:image src="1.jpg">
                Audio file <em>description</em>
            </e:image>
        </e:question>
    </e:section>
    <e:section cas-forbidden="true">
        <e:section-title/>
        <e:section-instruction>Cas forbidden section 2</e:section-instruction>
        <e:section-instruction>
            <p>Instructions 2</p>
        </e:section-instruction>
        <e:question>
            <e:question-title>Question with sub question</e:question-title>
            <e:question>
                <e:question-title>Sub question</e:question-title>
            </e:question>
        </e:question>
    </e:section>
    <e:section cas-forbidden="false">
        <e:section-title/>
        <e:section-instruction>Explicitly unset cas forbidden section</e:section-instruction>
        <e:question>
            <e:question-title/>
        </e:question>
    </e:section>
    <e:section cas-forbidden="true">
        <e:section-title/>
        <e:section-instruction>Cas forbidden section 3</e:section-instruction>
        <e:section-instruction>
            <p>Instructions 3</p>
        </e:section-instruction>
        <e:question>
            <e:question-title></e:question-title>
        </e:question>
    </e:section>
</e:exam>

=== digabi/exam-engine/packages/mastering/__tests__/fixtures/missing_attachments.xml
<?xml version="1.0" encoding="UTF-8"?>
<e:exam xmlns:e="http://ylioppilastutkinto.fi/exam.xsd" xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ylioppilastutkinto.fi/exam.xsd https://abitti.dev/schema/exam.xsd" exam-schema-version="0.5" date="2020-01-01">
  <e:exam-versions>
    <e:exam-version lang="fi-FI" exam-type="normal"/>
    <e:exam-version lang="fi-FI" exam-type="visually-impaired"/>
    <e:exam-version lang="fi-FI" exam-type="hearing-impaired"/>
  </e:exam-versions>
  <e:exam-instruction>
    <e:localization exam-type="normal visually-impaired">
      Tekstiä tavalliseen ja näkövammaisten kokeeseen.
    </e:localization>
    <e:localization exam-type="hearing-impaired">
      Tekstiä kuulovammaisten kokeeseen.
    </e:localization>
  </e:exam-instruction>
  <e:table-of-contents />
  <e:section>
    <e:section-title>Kuuntelutehtävät</e:section-title>
    <e:question>
      <e:question-title>Kaikille yhteinen tehtävä</e:question-title>
      <e:external-material exam-type="normal">
      <e:attachment name="1A">
        <e:attachment-title>
            <e:localization lang="fi-FI">Kuva: Puuveistokset</e:localization>
        </e:attachment-title>

        <e:reference>
          <e:author>
            <e:localization lang="fi-FI">YTL</e:localization>
          </e:author>
        </e:reference>
      </e:attachment>
    </e:external-material>
    <e:question-instruction>
      <e:localization lang="fi-FI" exam-type="normal">
          Katso kuva <e:attachment-link type="short" ref="1A"/>.
      </e:localization>

      <e:localization lang="fi-FI" exam-type="visually-impaired">
        Linkkiä <e:attachment-link type="short" ref="1A"/> ei löydy.
      </e:localization>

      <e:localization lang="fi-FI" exam-type="hearing-impaired">
        Linkkiä <e:attachment-link type="short" ref="1A"/> ei löydy.
      </e:localization>

    </e:question-instruction><e:localization lang="fi-FI" exam-type="normal"/>
    </e:question>
    <e:question exam-type="normal hearing-impaired">
      <e:question-title>Kuuntelutehtävä</e:question-title>
    </e:question>
    <e:question exam-type="visually-impaired">
      <e:question-title>Näkövammaisten korvaava kuuntelutehtävä</e:question-title>
    </e:question>
  </e:section>
  <e:section>
    <e:section-title>Kirjalliset tehtävät</e:section-title>
    <e:question exam-type="normal hearing-impaired">
      <e:question-title>Kirjallinen tehtävä</e:question-title>
    </e:question>
    <e:question exam-type="visually-impaired">
      <e:question-title>Näkövammaisten korvaava kirjallinen tehtävä</e:question-title>
    </e:question>
  </e:section>
</e:exam>

=== digabi/exam-engine/packages/mastering/__tests__/fixtures/cas.xml
<?xml version="1.0" encoding="UTF-8"?>
<e:exam xmlns:e="http://ylioppilastutkinto.fi/exam.xsd" xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ylioppilastutkinto.fi/exam.xsd https://abitti.dev/schema/exam.xsd" exam-schema-version="0.5">
    <e:exam-versions>
        <e:exam-version lang="fi-FI"/>
    </e:exam-versions>
    <e:exam-title>Cas forbidden</e:exam-title>
    <e:exam-instruction/>
    <e:table-of-contents/>
    <e:section cas-forbidden="true">
        <e:section-title>First section</e:section-title>
    </e:section>
    <e:section cas-forbidden="false">
        <e:section-title>Second section</e:section-title>
    </e:section>
    <e:section>
        <e:section-title>Third section</e:section-title>
    </e:section>
</e:exam>

=== digabi/exam-engine/packages/mastering/__tests__/fixtures/unallowed_max_length.xml
<?xml version="1.0" encoding="UTF-8"?>
<e:exam xmlns:e="http://ylioppilastutkinto.fi/exam.xsd" xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ylioppilastutkinto.fi/exam.xsd https://abitti.dev/schema/exam.xsd" exam-schema-version="0.5" date="2020-01-01">
  <e:exam-versions>
    <e:exam-version lang="fi-FI" exam-type="normal"/>
  </e:exam-versions>
  <e:exam-instruction>
    <e:localization exam-type="normal">
      Tekstiä tavalliseen ja näkövammaisten kokeeseen.
    </e:localization>
  </e:exam-instruction>
  <e:table-of-contents />

  <e:section>
    <e:section-title>Tehtävä</e:section-title>
    <e:question>
        <e:question-title>
            <e:localization lang="fi-FI">Otsikko</e:localization>
        </e:question-title>

        <e:question-instruction>
            <e:localization lang="fi-FI" exam-type="normal">
                Kysymys
            </e:localization>
        </e:question-instruction>
        <e:localization lang="fi-FI" exam-type="normal"/>
            <e:text-answer type="single-line" max-score="12" max-length="111">
            <e:answer-grading-instruction>
            <e:localization lang="fi-FI">
              Ohje
            </e:localization>
        </e:answer-grading-instruction>
    </e:text-answer>
  </e:question>
</e:section>
</e:exam>

=== digabi/exam-engine/packages/mastering/__tests__/fixtures/accepted_answer_without_score.xml
<?xml version="1.0" encoding="UTF-8"?>
<e:exam xmlns:e="http://ylioppilastutkinto.fi/exam.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/1999/xhtml" xsi:schemaLocation="http://ylioppilastutkinto.fi/exam.xsd exam.xsd" exam-schema-version="0.3" date="2018-09-29" exam-code="FF" exam-stylesheet="custom.css">
  <e:exam-versions>
      <e:exam-version lang="fi-FI"/>
  </e:exam-versions>
  <e:exam-title>Produktiivinen aukko ilman pisteitä</e:exam-title>
  <e:section>
    <e:section-title>Ensimmäinen osa</e:section-title>
    <e:question>
      <e:question-title>Produktiivinen aukko</e:question-title>
      <e:hints>
        <e:scored-text-answer>
          <e:accepted-answer>Pisteetön vaihtoehto</e:accepted-answer>
        </e:scored-text-answer>
      </e:hints>
    </e:question>
  </e:section>
</e:exam>

=== digabi/exam-engine/testi/exam.xml
<?xml version="1.0" encoding="utf-8" ?>
<e:exam xmlns:e="http://ylioppilastutkinto.fi/exam.xsd" xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ylioppilastutkinto.fi/exam.xsd https://abitti.dev/schema/exam.xsd" exam-schema-version="0.5">
    <e:exam-versions>
        <e:exam-version lang="fi-FI" />
    </e:exam-versions>

    <e:exam-title>Exam title</e:exam-title>

    <e:exam-instruction>
        Exam instructions.
    </e:exam-instruction>

    <e:table-of-contents />

    <e:section>
        <e:section-title>Section title</e:section-title>

        <e:question>
            <e:question-title>Question title</e:question-title>
            <e:question-instruction>Question instructions</e:question-instruction>
            <e:text-answer max-score="10" type="rich-text" />
        </e:question>
    </e:section>
</e:exam>

=== digabi/exam-engine/packages/mastering/__tests__/fixtures/choice_answer_with_no_answer.xml
<?xml version="1.0" encoding="UTF-8"?>
<e:exam xmlns:e="http://ylioppilastutkinto.fi/exam.xsd" xmlns="http://www.w3.org/1999/xhtml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ylioppilastutkinto.fi/exam.xsd https://abitti.dev/schema/exam.xsd" exam-schema-version="0.5" date="2020-01-01" exam-code="A" day-code="X">
  <e:exam-versions>
    <e:exam-version lang="fi-FI"/>
    <e:exam-version lang="sv-FI"/>
  </e:exam-versions>
  <e:exam-title/>
  <e:exam-instruction/>
  <e:section>
    <e:section-title/>
    <e:question>
      <e:question-title></e:question-title>
      <e:choice-answer>
        <e:choice-answer-option>A</e:choice-answer-option>
        <e:choice-answer-option>B</e:choice-answer-option>
        <e:choice-answer-option>C</e:choice-answer-option>
        <e:choice-answer-option type="no-answer">En vastaa</e:choice-answer-option>
      </e:choice-answer>
    </e:question>
  </e:section>
</e:exam>
